# Generated by Django 5.2.7 on 2025-11-05 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GachaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gacha_type', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_pity', models.IntegerField(default=90)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='items/')),
                ('wiki', models.URLField()),
                ('rarity', models.IntegerField()),
                ('eng_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='paths/')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gacha_id', models.IntegerField(unique=True)),
                ('gacha_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warps.gachatype')),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warps.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warps.itemtype'),
        ),
        migrations.AddField(
            model_name='item',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warps.path'),
        ),
        migrations.CreateModel(
            name='Warp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warp_id', models.IntegerField(unique=True)),
                ('uid', models.IntegerField()),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('gacha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warps.banner')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warps.item')),
            ],
        ),
    ]
