# Generated by Django 6.0.2 on 2026-04-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warptracker', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='warp',
            name='pity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
